import { getModel, getVisualModel } from "@/lib/openaiClient";

export async function GET() {
  return Response.json({
    status: "ok",
    version: "2.1.2-beta",
    hasApiKey: Boolean(process.env.OPENAI_API_KEY),
    model: getModel(),
    visualModel: getVisualModel(),
    reasoningEffort: process.env.OPENAI_REASONING_EFFORT || "low",
    accessProtected: Boolean(process.env.APP_ACCESS_CODE),
    adaptivePrecedent: true,
    analysisDrawer: true,
    chatAnalysisDrawer: true,
    assumptionTrace: true,
    judgmentOS: true,
    factOpinionSeparation: true,
    decisionOwnership: true,
    defensibilityTrace: true,
    responseGuard: true,
    reviewCycle: true,
    issueFixSuggestions: true,
    versionComparison: true,
    evidenceLocator: true,
    feedbackAccuracy: true,
    submissionPackage: true,
    largeFileUpload: true,
    visualDocumentReview: true,
    pdfVisionOcr: true,
    presentationImageOcr: true,
    chartXmlExtraction: true,
    blobConfigured: Boolean(process.env.BLOB_STORE_ID),
    blobAuthMode: process.env.BLOB_STORE_ID ? "oidc-direct-signed-url" : "not-configured",
    blobStoreIdConfigured: Boolean(process.env.BLOB_STORE_ID),
    blobWebhookKeyConfigured: Boolean(process.env.BLOB_WEBHOOK_PUBLIC_KEY),
    maxFileMB: 200,
    maxBatchMB: 300,
  });
}
